# Use this Dockerfile if you build locally and dont have enough RAM (exit status 137 on build)
# This Dockerfile expects you to have done the npm install and npm build beforehand

FROM registry.access.redhat.com/ubi8/nginx-118

COPY ./www/ .
COPY nginx.conf /etc/nginx/nginx.conf

#Run script uses standard ways to run the application
CMD nginx -g "daemon off;"
